//product mockup data
import 'package:fashion/models/category.dart';
import 'package:fashion/models/product.dart';

final List<Product> productMockup = [
  Product(
    id: 1,
    title: "Lacoste Shirt",
    calories: 175,
    prices: [
      PriceItem("", 10.99),
    ],
    options: [],
    description:
        "Lorem ipsum dolor sit amet. Qui minima inventore vel nisi laudantium ut accusantium beatae aut quas sint ab nulla beatae et dolor autem? Quo quibusdam iste qui reiciendis enim aut ipsum facere.",
    category: Category(
      id: 1,
    ),
    cookDuration: 0,
    discount: 0,
    featured: false,
    rate: 4.6,
    favoriteCount: 15,
    orderCount: 164,
    image: "assets/images/items/c1.png",
    size: [
      SizeItem("S"),
      SizeItem("M"),
      SizeItem("L"),
      SizeItem("XL"),
      SizeItem("XXL"),
    ],
  ),
  Product(
    id: 2,
    title: "Polo Shirt",
    calories: 185,
    prices: [
      PriceItem("", 2.99),
    ],
    options: [
      OptionItem(
        "Color",
        [
          "Red",
          "Blue",
          "Black",
          "Grey",
        ],
        false,
      ),
    ],
    description:
        "Lorem ipsum dolor sit amet. Qui minima inventore vel nisi laudantium ut accusantium beatae aut quas sint ab nulla beatae et dolor autem? Quo quibusdam iste qui reiciendis enim aut ipsum facere.",
    category: Category(
      id: 1,
    ),
    cookDuration: 0,
    discount: 0,
    featured: false,
    image: "assets/images/items/c2.png",
    favoriteCount: 5,
    rate: 4.5,
    orderCount: 164,
    size: [
      SizeItem("S"),
      SizeItem("M"),
      SizeItem("L"),
      SizeItem("XL"),
      SizeItem("XXL"),
    ],
  ),
  Product(
    id: 3,
    title: "Black Dress",
    calories: 1200,
    prices: [
      PriceItem("", 9.99),
      //PriceItem("medium", 9.99),
      //PriceItem("large", 15.99),
    ],
    options: [
      // OptionItem(
      //   "Drink",
      //   [
      //     "coca cola",
      //     "sprite",
      //     "fanta",
      //     "pepsi",
      //   ],
      //   false,
      // ),
      // OptionItem(
      //   "Sauce",
      //   [
      //     "mayonnaise",
      //     "ketchup",
      //     "mexican sauce",
      //     "garlic pate",
      //   ],
      //   true,
      // ),
      // OptionItem(
      //   "Fried sides",
      //   [
      //     "potato fried",
      //     "yam fried",
      //   ],
      //   false,
      // ),
    ],
    description:
        "Lorem ipsum dolor sit amet. Qui minima inventore vel nisi laudantium ut accusantium beatae aut quas sint ab nulla beatae et dolor autem? Quo quibusdam iste qui reiciendis enim aut ipsum facere.",
    category: Category(
      id: 2,
    ),
    cookDuration: 60,
    discount: 0,
    featured: true,
    image: "assets/images/items/r10.png",
    favoriteCount: 12,
    rate: 4.6,
    orderCount: 188,
    size: [
      SizeItem("S"),
      SizeItem("M"),
      SizeItem("L"),
      SizeItem("XL"),
      SizeItem("XXL"),
    ],
  ),
  Product(
    id: 4,
    title: "Dress ",
    calories: 1400,
    prices: [
      PriceItem("", 4.99),
      //PriceItem("small", 4.99),
      //PriceItem("medium", 6.99),
      //PriceItem("large", 8.99),
    ],
    options: [
      // OptionItem(
      //   "Sauce",
      //   [
      //     "mayonnaise",
      //     "ketchup",
      //     "mexican sauce",
      //     "garlic pate",
      //   ],
      //   true,
      // ),
    ],
    description:
        "Lorem ipsum dolor sit amet. Qui minima inventore vel nisi laudantium ut accusantium beatae aut quas sint ab nulla beatae et dolor autem? Quo quibusdam iste qui reiciendis enim aut ipsum facere.",
    category: Category(
      id: 3,
    ),
    cookDuration: 25,
    discount: 0.1,
    featured: false,
    image: "assets/images/items/e2.png",
    favoriteCount: 19,
    rate: 4.4,
    orderCount: 182,
    size: [
      SizeItem("S"),
      SizeItem("M"),
      SizeItem("L"),
      SizeItem("XL"),
      SizeItem("XXL"),
    ],
  ),
  Product(
    id: 5,
    title: "Red Skirt",
    calories: 2400,
    prices: [
      PriceItem("", 6.99),
      //PriceItem("small", 6.99),
      //PriceItem("medium", 7.99),
      //PriceItem("large", 8.99),
    ],
    options: [
      // OptionItem(
      //   "Drink",
      //   [
      //     "coca cola",
      //     "sprite",
      //     "fanta",
      //     "pepsi",
      //   ],
      //   false,
      // ),
      // OptionItem(
      //   "Sauce",
      //   [
      //     "mayonnaise",
      //     "ketchup",
      //     "mexican sauce",
      //     "garlic pate",
      //   ],
      //   true,
      // ),
      // OptionItem(
      //   "Fried sides",
      //   [
      //     "potato fried",
      //     "yam fried",
      //   ],
      //   false,
      // ),
    ],
    description:
        "Lorem ipsum dolor sit amet. Qui minima inventore vel nisi laudantium ut accusantium beatae aut quas sint ab nulla beatae et dolor autem? Quo quibusdam iste qui reiciendis enim aut ipsum facere.",
    category: Category(
      id: 3,
    ),
    cookDuration: 30,
    discount: 0,
    featured: true,
    image: "assets/images/items/e8.png",
    favoriteCount: 3,
    rate: 4.5,
    orderCount: 107,
    size: [
      SizeItem("S"),
      SizeItem("M"),
      SizeItem("L"),
      SizeItem("XL"),
      SizeItem("XXL"),
    ],
  ),
  Product(
    id: 6,
    title: "Hawaii Shirt",
    calories: 2400,
    prices: [
      PriceItem("", 8.99),
      //PriceItem("medium", 8.99),
      //PriceItem("large", 9.99),
    ],
    options: [
      // OptionItem(
      //   "Sauce",
      //   [
      //     "mayonnaise",
      //     "ketchup",
      //     "mexican sauce",
      //     "garlic pate",
      //   ],
      //   true,
      // ),
    ],
    description:
        "Lorem ipsum dolor sit amet. Qui minima inventore vel nisi laudantium ut accusantium beatae aut quas sint ab nulla beatae et dolor autem? Quo quibusdam iste qui reiciendis enim aut ipsum facere.",
    category: Category(
      id: 3,
    ),
    cookDuration: 30,
    discount: 0,
    featured: false,
    image: "assets/images/items/g1.png",
    favoriteCount: 5,
    rate: 4.6,
    orderCount: 56,
    size: [
      SizeItem("S"),
      SizeItem("M"),
      SizeItem("L"),
      SizeItem("XL"),
      SizeItem("XXL"),
    ],
  ),
  Product(
    id: 7,
    title: "Armani Shirt",
    calories: 1800,
    prices: [
      PriceItem("", 7.99),
      //PriceItem("medium", 7.99),
      //PriceItem("large", 8.99),
    ],
    options: [
      // OptionItem(
      //   "Sauce",
      //   [
      //     "mayonnaise",
      //     "ketchup",
      //     "mexican sauce",
      //     "garlic pate",
      //   ],
      //   true,
      // ),
    ],
    description:
        "Lorem ipsum dolor sit amet. Qui minima inventore vel nisi laudantium ut accusantium beatae aut quas sint ab nulla beatae et dolor autem? Quo quibusdam iste qui reiciendis enim aut ipsum facere.",
    category: Category(
      id: 3,
    ),
    cookDuration: 30,
    discount: 0.25,
    featured: false,
    image: "assets/images/items/jj2.png",
    favoriteCount: 18,
    rate: 4.8,
    orderCount: 167,
    size: [
      SizeItem("S"),
      SizeItem("M"),
      SizeItem("L"),
      SizeItem("XL"),
      SizeItem("XXL"),
    ],
  ),
  Product(
    id: 8,
    title: "Pants slim",
    calories: 1750,
    prices: [
      PriceItem("", 2.99),
      //PriceItem("half chicken", 2.99),
      //PriceItem("Whole chicken", 3.99),
    ],
    options: [
      // OptionItem(
      //   "Fried sides",
      //   [
      //     "potato fried",
      //     "yam fried",
      //   ],
      //   false,
      // ),
    ],
    description:
        "Lorem ipsum dolor sit amet. Qui minima inventore vel nisi laudantium ut accusantium beatae aut quas sint ab nulla beatae et dolor autem? Quo quibusdam iste qui reiciendis enim aut ipsum facere.",
    category: Category(
      id: 1,
    ),
    cookDuration: 20,
    discount: 0.25,
    featured: false,
    image: "assets/images/items/pp60.png",
    favoriteCount: 15,
    rate: 4.4,
    orderCount: 195,
    size: [
      SizeItem("S"),
      SizeItem("M"),
      SizeItem("L"),
      SizeItem("XL"),
      SizeItem("XXL"),
    ],
  ),
  Product(
    id: 9,
    title: "Pants slim",
    calories: 2150,
    prices: [
      PriceItem("", 3.99),
      //PriceItem("half chicken", 3.99),
      //PriceItem("Whole chicken", 4.99),
    ],
    options: [
      // OptionItem(
      //   "Fried sides",
      //   [
      //     "potato fried",
      //     "yam fried",
      //   ],
      //   false,
      // ),
    ],
    description:
        "Lorem ipsum dolor sit amet. Qui minima inventore vel nisi laudantium ut accusantium beatae aut quas sint ab nulla beatae et dolor autem? Quo quibusdam iste qui reiciendis enim aut ipsum facere.",
    category: Category(
      id: 1,
    ),
    cookDuration: 20,
    discount: 0,
    featured: false,
    image: "assets/images/items/jj6.png",
    favoriteCount: 9,
    rate: 4.1,
    orderCount: 88,
    size: [
      SizeItem("S"),
      SizeItem("M"),
      SizeItem("L"),
      SizeItem("XL"),
      SizeItem("XXL"),
    ],
  ),
  Product(
    id: 10,
    title: "Shirts Slim",
    calories: 1950,
    prices: [
      PriceItem("", 3.99),
      //PriceItem("half chicken", 3.99),
      //PriceItem("Whole chicken", 4.99),
    ],
    options: [
      // OptionItem(
      //   "Fried sides",
      //   [
      //     "potato fried",
      //     "yam fried",
      //   ],
      //   false,
      // ),
    ],
    description:
        "Lorem ipsum dolor sit amet. Qui minima inventore vel nisi laudantium ut accusantium beatae aut quas sint ab nulla beatae et dolor autem? Quo quibusdam iste qui reiciendis enim aut ipsum facere.",
    category: Category(
      id: 1,
    ),
    cookDuration: 25,
    discount: 0,
    featured: false,
    image: "assets/images/items/c8.png",
    favoriteCount: 11,
    rate: 4.7,
    orderCount: 126,
    size: [
      SizeItem("S"),
      SizeItem("M"),
      SizeItem("L"),
      SizeItem("XL"),
      SizeItem("XXL"),
    ],
  ),
  Product(
    id: 11,
    title: "Shirts slim",
    calories: 900,
    prices: [
      PriceItem("", 2.99),
    ],
    options: [],
    description:
        "Lorem ipsum dolor sit amet. Qui minima inventore vel nisi laudantium ut accusantium beatae aut quas sint ab nulla beatae et dolor autem? Quo quibusdam iste qui reiciendis enim aut ipsum facere.",
    category: Category(
      id: 1,
    ),
    cookDuration: 30,
    discount: 0,
    featured: false,
    image: "assets/images/items/c6.png",
    favoriteCount: 5,
    rate: 4.8,
    orderCount: 53,
    size: [
      SizeItem("S"),
      SizeItem("M"),
      SizeItem("L"),
      SizeItem("XL"),
      SizeItem("XXL"),
    ],
  ),
  Product(
    id: 12,
    title: "Skirts Cool",
    calories: 950,
    prices: [
      PriceItem("", 3.99),
    ],
    options: [],
    description:
        "Lorem ipsum dolor sit amet. Qui minima inventore vel nisi laudantium ut accusantium beatae aut quas sint ab nulla beatae et dolor autem? Quo quibusdam iste qui reiciendis enim aut ipsum facere.",
    category: Category(
      id: 2,
    ),
    cookDuration: 30,
    discount: 0,
    featured: false,
    image: "assets/images/items/r50.png",
    favoriteCount: 8,
    rate: 4.2,
    orderCount: 70,
    size: [
      SizeItem("S"),
      SizeItem("M"),
      SizeItem("L"),
      SizeItem("XL"),
      SizeItem("XXL"),
    ],
  ),
  Product(
    id: 13,
    title: "Dress Nike",
    calories: 900,
    prices: [
      PriceItem("", 5.99),
    ],
    options: [],
    description:
        "Lorem ipsum dolor sit amet. Qui minima inventore vel nisi laudantium ut accusantium beatae aut quas sint ab nulla beatae et dolor autem? Quo quibusdam iste qui reiciendis enim aut ipsum facere.",
    category: Category(
      id: 2,
    ),
    cookDuration: 45,
    discount: 0,
    featured: false,
    image: "assets/images/items/r41.png",
    favoriteCount: 16,
    rate: 4.5,
    orderCount: 100,
    size: [
      SizeItem("S"),
      SizeItem("M"),
      SizeItem("L"),
      SizeItem("XL"),
      SizeItem("XXL"),
    ],
  ),
  Product(
    id: 14,
    title: "Dress Gucci",
    calories: 900,
    prices: [
      PriceItem("", 1.99),
    ],
    options: [],
    description:
        "Lorem ipsum dolor sit amet. Qui minima inventore vel nisi laudantium ut accusantium beatae aut quas sint ab nulla beatae et dolor autem? Quo quibusdam iste qui reiciendis enim aut ipsum facere.",
    category: Category(
      id: 2,
    ),
    cookDuration: 30,
    discount: 0,
    featured: false,
    image: "assets/images/items/r42.png",
    favoriteCount: 16,
    rate: 4.5,
    orderCount: 100,
    size: [
      SizeItem("S"),
      SizeItem("M"),
      SizeItem("L"),
      SizeItem("XL"),
      SizeItem("XXL"),
    ],
  ),
  Product(
    id: 15,
    title: "Dress Nike",
    calories: 20,
    prices: [
      PriceItem("", 3.99),
      //PriceItem("25 cl", 0.99),
      // PriceItem("35 cl", 1.99),
    ],
    options: [
      // OptionItem(
      //   "Recipe",
      //   [
      //     "Simple",
      //     "Cream",
      //   ],
      //   false,
      // ),
      // OptionItem(
      //   "Sugar ?",
      //   [
      //     "No",
      //     "Yes",
      //   ],
      //   false,
      // ),
    ],
    description:
        "Lorem ipsum dolor sit amet. Qui minima inventore vel nisi laudantium ut accusantium beatae aut quas sint ab nulla beatae et dolor autem? Quo quibusdam iste qui reiciendis enim aut ipsum facere.",
    category: Category(
      id: 2,
    ),
    cookDuration: 5,
    discount: 0,
    featured: false,
    image: "assets/images/items/r45.png",
    favoriteCount: 13,
    rate: 4.7,
    orderCount: 188,
    size: [
      SizeItem("S"),
      SizeItem("M"),
      SizeItem("L"),
      SizeItem("XL"),
      SizeItem("XXL"),
    ],
  ),
  Product(
    id: 16,
    title: "Panties",
    calories: 30,
    prices: [
      PriceItem("", 5.99),
      //PriceItem("33 cl", 0.99),
      //PriceItem("50 cl", 1.99),
    ],
    options: [
      // OptionItem(
      //   "Recipe",
      //   [
      //     "Simple",
      //     "Cream",
      //   ],
      //   false,
      // ),
      // OptionItem(
      //   "Sugar ?",
      //   [
      //     "No",
      //     "Yes",
      //   ],
      //   false,
      // ),
    ],
    description:
        "Lorem ipsum dolor sit amet. Qui minima inventore vel nisi laudantium ut accusantium beatae aut quas sint ab nulla beatae et dolor autem? Quo quibusdam iste qui reiciendis enim aut ipsum facere.",
    category: Category(
      id: 1,
    ),
    cookDuration: 5,
    discount: 0,
    featured: false,
    image: "assets/images/items/cu1.png",
    favoriteCount: 17,
    rate: 4.2,
    orderCount: 178,
    size: [
      SizeItem("S"),
      SizeItem("M"),
      SizeItem("L"),
      SizeItem("XL"),
      SizeItem("XXL"),
    ],
  ),
  Product(
    id: 17,
    title: "Panties Red",
    calories: 450,
    prices: [
      PriceItem("", 2.99),
    ],
    options: [
      // OptionItem(
      //   "Chocolate",
      //   ["Nutella", "Choco Quick", "ChocoMilk"],
      //   false,
      // ),
      // OptionItem(
      //   "Sugar",
      //   ["No sugar", "Honey", "sugar"],
      //   false,
      // ),
    ],
    description:
        "Lorem ipsum dolor sit amet. Qui minima inventore vel nisi laudantium ut accusantium beatae aut quas sint ab nulla beatae et dolor autem? Quo quibusdam iste qui reiciendis enim aut ipsum facere.",
    category: Category(
      id: 1,
    ),
    cookDuration: 15,
    discount: 0,
    featured: false,
    image: "assets/images/items/cu3.png",
    favoriteCount: 11,
    rate: 4.4,
    orderCount: 115,
    size: [
      SizeItem("S"),
      SizeItem("M"),
      SizeItem("L"),
      SizeItem("XL"),
      SizeItem("XXL"),
    ],
  ),
  Product(
    id: 18,
    title: "Pants Fashion",
    calories: 850,
    prices: [
      PriceItem("", 3.99),
    ],
    options: [],
    description:
        "Lorem ipsum dolor sit amet. Qui minima inventore vel nisi laudantium ut accusantium beatae aut quas sint ab nulla beatae et dolor autem? Quo quibusdam iste qui reiciendis enim aut ipsum facere.",
    category: Category(
      id: 1,
    ),
    cookDuration: 15,
    discount: 0,
    featured: false,
    image: "assets/images/items/p2.png",
    favoriteCount: 20,
    rate: 4.2,
    orderCount: 126,
    size: [
      SizeItem("S"),
      SizeItem("M"),
      SizeItem("L"),
      SizeItem("XL"),
      SizeItem("XXL"),
    ],
  ),
  Product(
    id: 19,
    title: "Flying Skirt",
    calories: 80,
    prices: [
      PriceItem("", 4.99),
    ],
    options: [
      // OptionItem(
      //   "Sugar",
      //   ["No sugar", "1 Stick", "2 Sticks", "3 Sticks"],
      //   false,
      // ),
    ],
    description:
        "Lorem ipsum dolor sit amet. Qui minima inventore vel nisi laudantium ut accusantium beatae aut quas sint ab nulla beatae et dolor autem? Quo quibusdam iste qui reiciendis enim aut ipsum facere.",
    category: Category(
      id: 2,
    ),
    cookDuration: 0,
    discount: 0,
    featured: false,
    image: "assets/images/items/r23.png",
    favoriteCount: 20,
    rate: 4.2,
    orderCount: 126,
    size: [
      SizeItem("S"),
      SizeItem("M"),
      SizeItem("L"),
      SizeItem("XL"),
      SizeItem("XXL"),
    ],
  ),
  Product(
    id: 20,
    title: "Long Skirt",
    calories: 160,
    prices: [
      PriceItem("", 8.99),
      //PriceItem("33 cl", 0.99),
      //PriceItem("50 cl", 1.99),
    ],
    options: [],
    description:
        "Lorem ipsum dolor sit amet. Qui minima inventore vel nisi laudantium ut accusantium beatae aut quas sint ab nulla beatae et dolor autem? Quo quibusdam iste qui reiciendis enim aut ipsum facere.",
    category: Category(
      id: 2,
    ),
    cookDuration: 10,
    discount: 0,
    featured: false,
    image: "assets/images/items/r49.png",
    favoriteCount: 5,
    rate: 4.7,
    orderCount: 346,
    size: [
      SizeItem("S"),
      SizeItem("M"),
      SizeItem("L"),
      SizeItem("XL"),
      SizeItem("XXL"),
    ],
  ),
  Product(
    id: 21,
    title: "Girl Dress",
    calories: 600,
    prices: [
      PriceItem("", 3.59),
      //PriceItem("250 g", 0.99),
      // PriceItem("500 g", 1.89),
      // PriceItem("700 g", 2.5),
    ],
    options: [],
    description:
        "Lorem ipsum dolor sit amet. Qui minima inventore vel nisi laudantium ut accusantium beatae aut quas sint ab nulla beatae et dolor autem? Quo quibusdam iste qui reiciendis enim aut ipsum facere.",
    category: Category(
      id: 3,
    ),
    cookDuration: 10,
    discount: 0,
    featured: true,
    image: "assets/images/items/r17.png",
    favoriteCount: 28,
    rate: 4.8,
    orderCount: 241,
    size: [
      SizeItem("S"),
      SizeItem("M"),
      SizeItem("L"),
      SizeItem("XL"),
      SizeItem("XXL"),
    ],
  ),
  Product(
    id: 22,
    title: "Dress Tkf",
    calories: 1100,
    prices: [
      PriceItem("", 5.59),
    ],
    options: [
      // OptionItem(
      //   "Sauce",
      //   [
      //     "mayonnaise",
      //     "ketchup",
      //     "mexican sauce",
      //     "garlic pate",
      //   ],
      //   true,
      // ),
    ],
    description:
        "Lorem ipsum dolor sit amet. Qui minima inventore vel nisi laudantium ut accusantium beatae aut quas sint ab nulla beatae et dolor autem? Quo quibusdam iste qui reiciendis enim aut ipsum facere.",
    category: Category(
      id: 2,
    ),
    cookDuration: 15,
    discount: 0,
    featured: true,
    image: "assets/images/items/r20.png",
    favoriteCount: 21,
    rate: 4.3,
    orderCount: 193,
    size: [
      SizeItem("S"),
      SizeItem("M"),
      SizeItem("L"),
      SizeItem("XL"),
      SizeItem("XXL"),
    ],
  ),
  Product(
    id: 23,
    title: "Dress Skinny",
    calories: 1100,
    prices: [
      PriceItem("", 4.29),
    ],
    options: [
      // OptionItem(
      //   "Sauce",
      //   [
      //     "mayonnaise",
      //     "ketchup",
      //     "mexican sauce",
      //     "garlic pate",
      //   ],
      //   true,
      // ),
    ],
    description:
        "Lorem ipsum dolor sit amet. Qui minima inventore vel nisi laudantium ut accusantium beatae aut quas sint ab nulla beatae et dolor autem? Quo quibusdam iste qui reiciendis enim aut ipsum facere.",
    category: Category(
      id: 2,
    ),
    cookDuration: 15,
    discount: 0,
    featured: false,
    image: "assets/images/items/r5.png",
    favoriteCount: 23,
    rate: 4.4,
    orderCount: 203,
    size: [
      SizeItem("S"),
      SizeItem("M"),
      SizeItem("L"),
      SizeItem("XL"),
      SizeItem("XXL"),
    ],
  ),
  Product(
    id: 24,
    title: "Dress Hard",
    calories: 750,
    prices: [
      PriceItem("", 2.49),
    ],
    options: [],
    description:
        "Lorem ipsum dolor sit amet. Qui minima inventore vel nisi laudantium ut accusantium beatae aut quas sint ab nulla beatae et dolor autem? Quo quibusdam iste qui reiciendis enim aut ipsum facere.",
    category: Category(
      id: 2,
    ),
    cookDuration: 25,
    discount: 0,
    featured: false,
    image: "assets/images/items/i1.png",
    favoriteCount: 23,
    rate: 4.7,
    orderCount: 93,
    size: [
      SizeItem("S"),
      SizeItem("M"),
      SizeItem("L"),
      SizeItem("XL"),
      SizeItem("XXL"),
    ],
  ),
  Product(
    id: 25,
    title: "Baby Dress",
    calories: 750,
    prices: [
      PriceItem("", 2.59),
    ],
    options: [],
    description:
        "Lorem ipsum dolor sit amet. Qui minima inventore vel nisi laudantium ut accusantium beatae aut quas sint ab nulla beatae et dolor autem? Quo quibusdam iste qui reiciendis enim aut ipsum facere.",
    category: Category(
      id: 3,
    ),
    cookDuration: 20,
    discount: 0,
    featured: false,
    image: "assets/images/items/r28.png",
    favoriteCount: 7,
    rate: 4.7,
    orderCount: 93,
    size: [
      SizeItem("S"),
      SizeItem("M"),
      SizeItem("L"),
      SizeItem("XL"),
      SizeItem("XXL"),
    ],
  ),
  Product(
    id: 26,
    title: "Pants",
    calories: 1100,
    prices: [
      PriceItem("", 5.99),
      //PriceItem("small", 5.99),
      // PriceItem("medium", 6.99),
      // PriceItem("large", 7.99),
    ],
    options: [
      // OptionItem(
      //   "Sauce",
      //   [
      //     "mayonnaise",
      //     "ketchup",
      //     "mexican sauce",
      //     "garlic pate",
      //   ],
      //   true,
      // ),
    ],
    description:
        "Lorem ipsum dolor sit amet. Qui minima inventore vel nisi laudantium ut accusantium beatae aut quas sint ab nulla beatae et dolor autem? Quo quibusdam iste qui reiciendis enim aut ipsum facere.",
    category: Category(
      id: 1,
    ),
    cookDuration: 45,
    discount: 0,
    featured: false,
    image: "assets/images/items/p61.png",
    favoriteCount: 7,
    rate: 4.4,
    orderCount: 82,
    size: [
      SizeItem("S"),
      SizeItem("M"),
      SizeItem("L"),
      SizeItem("XL"),
      SizeItem("XXL"),
    ],
  ),
  Product(
    id: 27,
    title: "Pants Gxs",
    calories: 1000,
    prices: [
      PriceItem("", 6.59),
      //PriceItem("small", 6),
      // PriceItem("medium", 7),
      // PriceItem("large", 8),
    ],
    options: [
      // OptionItem(
      //   "Sauce",
      //   [
      //     "mayonnaise",
      //     "ketchup",
      //     "mexican sauce",
      //     "garlic pate",
      //   ],
      //   true,
      // ),
    ],
    description:
        "Lorem ipsum dolor sit amet. Qui minima inventore vel nisi laudantium ut accusantium beatae aut quas sint ab nulla beatae et dolor autem? Quo quibusdam iste qui reiciendis enim aut ipsum facere.",
    category: Category(
      id: 1,
    ),
    cookDuration: 45,
    discount: 0.2,
    featured: true,
    image: "assets/images/items/jj4.png",
    favoriteCount: 7,
    rate: 4.7,
    orderCount: 147,
    size: [
      SizeItem("S"),
      SizeItem("M"),
      SizeItem("L"),
      SizeItem("XL"),
      SizeItem("XXL"),
    ],
  ),
  Product(
    id: 28,
    title: "Shirt Tkf",
    calories: 1250,
    prices: [
      PriceItem("", 5.99),
      //PriceItem("small", 5.99),
      // PriceItem("medium", 6.99),
      // PriceItem("large", 7.99),
    ],
    options: [
      // OptionItem(
      //   "Sauce",
      //   [
      //     "mayonnaise",
      //     "ketchup",
      //     "mexican sauce",
      //     "garlic pate",
      //   ],
      //   true,
      // ),
    ],
    description:
        "Lorem ipsum dolor sit amet. Qui minima inventore vel nisi laudantium ut accusantium beatae aut quas sint ab nulla beatae et dolor autem? Quo quibusdam iste qui reiciendis enim aut ipsum facere.",
    category: Category(
      id: 1,
    ),
    cookDuration: 45,
    discount: 0.2,
    featured: true,
    image: "assets/images/items/cu2.png",
    favoriteCount: 11,
    rate: 4.7,
    orderCount: 197,
    size: [
      SizeItem("S"),
      SizeItem("M"),
      SizeItem("L"),
      SizeItem("XL"),
      SizeItem("XXL"),
    ],
  ),
  Product(
    id: 29,
    title: "Sexy Dress",
    calories: 1150,
    prices: [
      PriceItem("", 5.50),
      //PriceItem("small", 5.5),
      // PriceItem("medium", 6.5),
      // PriceItem("large", 7.5),
    ],
    options: [
      // OptionItem(
      //   "Sauce",
      //   [
      //     "mayonnaise",
      //     "ketchup",
      //     "mexican sauce",
      //     "garlic pate",
      //   ],
      //   true,
      // ),
    ],
    description:
        "Lorem ipsum dolor sit amet. Qui minima inventore vel nisi laudantium ut accusantium beatae aut quas sint ab nulla beatae et dolor autem? Quo quibusdam iste qui reiciendis enim aut ipsum facere.",
    category: Category(
      id: 2,
    ),
    cookDuration: 40,
    discount: 0,
    featured: false,
    image: "assets/images/items/e7.png",
    favoriteCount: 7,
    rate: 4.3,
    orderCount: 127,
    size: [
      SizeItem("S"),
      SizeItem("M"),
      SizeItem("L"),
      SizeItem("XL"),
      SizeItem("XXL"),
    ],
  ),
  Product(
    id: 30,
    title: " Short Skirt",
    calories: 850,
    prices: [
      PriceItem("", 8.79),
      //PriceItem("small", 0.79),
      //PriceItem("medium", 0.99),
    ],
    options: [
      // OptionItem(
      //   "Sauce",
      //   [
      //     "mayonnaise",
      //     "ketchup",
      //     "mexican sauce",
      //     "garlic pate",
      //   ],
      //   true,
      // ),
    ],
    description:
        "Lorem ipsum dolor sit amet. Qui minima inventore vel nisi laudantium ut accusantium beatae aut quas sint ab nulla beatae et dolor autem? Quo quibusdam iste qui reiciendis enim aut ipsum facere.",
    category: Category(
      id: 2,
    ),
    cookDuration: 10,
    discount: 0,
    featured: false,
    image: "assets/images/items/jj11.png",
    favoriteCount: 7,
    rate: 4.3,
    orderCount: 207,
    size: [
      SizeItem("S"),
      SizeItem("M"),
      SizeItem("L"),
      SizeItem("XL"),
      SizeItem("XXL"),
    ],
  ),
  Product(
    id: 31,
    title: " Short Skirt Dxs",
    calories: 950,
    prices: [
      PriceItem("", 9.89),
      //PriceItem("small", 0.89),
      //PriceItem("medium", 1.19),
    ],
    options: [
      // OptionItem(
      //   "Sauce",
      //   [
      //     "mayonnaise",
      //     "ketchup",
      //     "mexican sauce",
      //     "garlic pate",
      //   ],
      //   true,
      // ),
    ],
    description:
        "Lorem ipsum dolor sit amet. Qui minima inventore vel nisi laudantium ut accusantium beatae aut quas sint ab nulla beatae et dolor autem? Quo quibusdam iste qui reiciendis enim aut ipsum facere.",
    category: Category(
      id: 2,
    ),
    cookDuration: 10,
    discount: 0,
    featured: false,
    image: "assets/images/items/jj8.png",
    favoriteCount: 19,
    rate: 4.8,
    orderCount: 217,
    size: [
      SizeItem("S"),
      SizeItem("M"),
      SizeItem("L"),
      SizeItem("XL"),
      SizeItem("XXL"),
    ],
  ),
  Product(
    id: 32,
    title: "Skinny Dress",
    calories: 300,
    prices: [
      PriceItem("", 3.45),
    ],
    options: [],
    description:
        "Lorem ipsum dolor sit amet. Qui minima inventore vel nisi laudantium ut accusantium beatae aut quas sint ab nulla beatae et dolor autem? Quo quibusdam iste qui reiciendis enim aut ipsum facere.",
    category: Category(
      id: 2,
    ),
    cookDuration: 10,
    discount: 0,
    featured: false,
    image: "assets/images/items/jj6.png",
    favoriteCount: 7,
    rate: 4.8,
    orderCount: 23,
    size: [
      SizeItem("S"),
      SizeItem("M"),
      SizeItem("L"),
      SizeItem("XL"),
      SizeItem("XXL"),
    ],
  ),
  Product(
    id: 33,
    title: "Pants Women",
    calories: 300,
    prices: [
      PriceItem("", 3.59),
    ],
    options: [],
    description:
        "Lorem ipsum dolor sit amet. Qui minima inventore vel nisi laudantium ut accusantium beatae aut quas sint ab nulla beatae et dolor autem? Quo quibusdam iste qui reiciendis enim aut ipsum facere.",
    category: Category(
      id: 2,
    ),
    cookDuration: 15,
    discount: 0,
    featured: false,
    image: "assets/images/items/jj7.png",
    favoriteCount: 7,
    rate: 4.3,
    orderCount: 33,
    size: [
      SizeItem("S"),
      SizeItem("M"),
      SizeItem("L"),
      SizeItem("XL"),
      SizeItem("XXL"),
    ],
  ),
  Product(
    id: 34,
    title: "Black Dress SKN",
    calories: 300,
    prices: [
      PriceItem("", 3.55),
    ],
    options: [],
    description:
        "Lorem ipsum dolor sit amet. Qui minima inventore vel nisi laudantium ut accusantium beatae aut quas sint ab nulla beatae et dolor autem? Quo quibusdam iste qui reiciendis enim aut ipsum facere.",
    category: Category(
      id: 2,
    ),
    cookDuration: 20,
    discount: 0,
    featured: false,
    image: "assets/images/items/r44.png",
    favoriteCount: 3,
    rate: 4.2,
    orderCount: 23,
    size: [
      SizeItem("S"),
      SizeItem("M"),
      SizeItem("L"),
      SizeItem("XL"),
      SizeItem("XXL"),
    ],
  ),
];
